/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "unit.check" instead.
 */

#include <check.h>

#include <stdio.h>
#include "s21_string.h"
#include <string.h>

START_TEST(s21_memchr_test) {
#line 6
    unsigned char src01[15]="1234567890";
    unsigned char src02[15]="1234567890";
    unsigned char src03[15]="1.3456789";
    ck_assert_str_eq(s21_memchr(src01, '4', 10), memchr(src01, '4', 10));
    ck_assert_str_eq(s21_memchr(src02, '7', 10), memchr(src02, '7', 10));
    ck_assert_str_eq(s21_memchr(src03, '.', 9), memchr(src03, '.', 9));
}
END_TEST
START_TEST(s21_memcmp_test) {
#line 14
    char src02[15] = "1234567890";
    char dst02[15] = "1234567890";
    ck_assert_int_eq(s21_memcmp(src02, dst02, 10), memcmp(src02, dst02, 10));
    char src03[10] = "1234567890";
    char dst03[10] = "4552723721";
    ck_assert_int_eq(s21_memcmp(src03, dst03, 10), memcmp(src03, dst03, 10));
    char src04[10] = "ABCD";
    char dst04[10] = " ";
    ck_assert_int_eq(s21_memcmp(src04, dst04, 5), memcmp(src04, dst04, 5));
}
END_TEST
START_TEST(s21_memcpy_test) {
#line 25
    unsigned char src[10]="123456";
    unsigned char dst[10]="";
    unsigned char src02[15]="123000000";
    unsigned char dst02[15]="023456001";
    unsigned char src03[15]="aaaaaaaaabbbbbb";
    unsigned char dst03[15]="bbbbbbbbbaaaaaa";
    unsigned char src04[15]="aaaaaaaa";
    unsigned char dst04[15]="12345678";
    ck_assert_str_eq(s21_memcpy(dst02, src02, 10), memcpy(dst02, src02, 10));
    ck_assert_str_eq(s21_memcpy(dst03, src03, 15), memcpy(dst03, src03, 15));
    ck_assert_str_eq(s21_memcpy(dst04, src04, 8), memcpy(dst04, src04, 8));
    ck_assert_str_eq(s21_memcpy(dst, src, 6), memcpy(dst, src, 6));
}
END_TEST
START_TEST(s21_memmove_test) {
#line 40
    unsigned char src999[10]="1234567890";
    char src91[24] = "vlvhvhvhjl";
    char src92[24] = "";
    char src95[27] = "123";
    char src96[27] = "8904567";
    ck_assert_str_eq(s21_memmove(&src999[4], &src999[3], 3), memmove(&src999[4], &src999[3], 3));
    ck_assert_str_eq(s21_memmove(src91, src92, 5), memmove(src91, src92, 5));
    ck_assert_str_eq(s21_memmove(src95, src96, 1), memmove(src95, src96, 1));
}
END_TEST
START_TEST(s21_memset_test) {
#line 50
    unsigned char src01[15]="1234567890";
    unsigned char src02[15]="12345";
    unsigned char src03[24]=" ";
    unsigned char src04[10]="";
    ck_assert_str_eq(s21_memset(src01, '1', 10), memset(src01, '1', 10));
    ck_assert_str_eq(s21_memset(src02, 'c', 5), memset(src02, 'c', 5));
    ck_assert_str_eq(s21_memset(src03, 't', 7), memset(src03, 't', 7));
    ck_assert_str_eq(s21_memset(src04, '!', 10), memset(src04, '!', 10));
}
END_TEST
START_TEST(s21_strcat_test) {
#line 60
    char app01[1024]="вторая строка";
    char dst01[1024]="первая строка";
    char app02[1024]=" ";
    char dst02[1024]=" ";
    char app03[1024]=" ";
    char dst03[1024]="222222222222";
    char app04[1024]=" ";
    char dst04[1024]="Good job!";
    char app05[1024]="55555";
    char dst05[1024]="Good job!";
    ck_assert_str_eq(s21_strcat(dst01, app01), strcat(dst01, app01));
    ck_assert_str_eq(s21_strcat(dst02, app02), strcat(dst02, app02));
    ck_assert_str_eq(s21_strcat(dst03, app03), strcat(dst03, app03));
    ck_assert_str_eq(s21_strcat(dst04, app04), strcat(dst04, app04));
    ck_assert_str_eq(s21_strcat(dst05, app05), strcat(dst05, app05));
}
END_TEST
START_TEST(s21_strncat_test) {
#line 77
    char src1[10]="000";
    char src2[10]="000";
    char app[10]="12345";
    char src3[10] = "abcd";
    char app1[10] = " ";
    char src4[10] = " ";
    char app2[10] = "";
    ck_assert_str_eq(s21_strncat(src1, app, 3), strncat(src1, app, 3));
    ck_assert_str_eq(s21_strncat(src2, app, 7), strncat(src2, app, 7));
    ck_assert_str_eq(s21_strncat(src3, app1, 2), strncat(src3, app1, 2));
    ck_assert_str_eq(s21_strncat(src4, app2, 9), strncat(src4, app2, 9));
    ck_assert_str_eq(s21_strncat(src3, app1, 1), strncat(src3, app1, 1));
    ck_assert_str_eq(s21_strncat(src4, app2, 0), strncat(src4, app2, 0));
}
END_TEST
START_TEST(s21_strncmp_test) {
#line 92
    char base[151] = "123456789";
    char base2[113] = "12345678954123515";
    char gal[9] = "";
    char gal2[35] = "ytrewrwgds";
    char gal3[9] = "ytwrw";
    char gal4[35] = "ytre wrwgds";
    ck_assert_int_eq(s21_strncmp(base, base2, 1), strncmp(base, base2, 1));
    ck_assert_int_eq(s21_strncmp(gal, gal2, 0), strncmp(gal, gal2, 0));
    ck_assert_int_eq(s21_strncmp(gal3, gal4, 3), strncmp(gal3, gal4, 3));
}
END_TEST
START_TEST(s21_strchr_test) {
#line 102
    char str234[11]="0123456789";
    char ch1 = '6';
    char ch2 = '6';
    char ch3 = ' ';
    ck_assert_pstr_eq(s21_strchr(str234, ch1), strchr(str234, ch1));
    ck_assert_pstr_eq(s21_strchr(str234, ch2), strchr(str234, ch2));
    ck_assert_pstr_eq(s21_strchr(str234, ch3), strchr(str234, ch3));
}
END_TEST
START_TEST(s21_strcmp_test) {
#line 111
    char str1[1024]="12345";
    char str2[1024]="12305";
    char str11[1024]="/gdrt";
    char str21[1024]="rvbt75";
    char str22[1024]="ABCDEF";
    char str99[1024]="234";
    ck_assert_int_eq(s21_strcmp(str1, str2), strcmp(str1, str2));
    ck_assert_int_eq(s21_strcmp(str11, str21), strcmp(str11, str21));
    ck_assert_int_eq(s21_strcmp(str22, str99), strcmp(str22, str99));
}
END_TEST
START_TEST(s21_strcpy_test) {
#line 123
    char src[1024]="первая строка\0вторая строка";
    char dst[1024]=" ";
    char src1[1024]=" ";
    char dst1[1024]=" ";
    char src2[1024]="234";
    char dst2[1024]="";
    char src3[1024]="fdr454gf";
    char dst3[1024]="h333e";
    ck_assert_str_eq(s21_strcpy(dst, src), strcpy(dst, src));
    ck_assert_str_eq(s21_strcpy(dst1, src1), strcpy(dst1, src1));
    ck_assert_str_eq(s21_strcpy(dst2, src2), strcpy(dst2, src2));
    ck_assert_str_eq(s21_strcpy(dst3, src3), strcpy(dst3, src3));
}
END_TEST
START_TEST(s21_strncpy_test) {
#line 139
    char src[10]="12345\0006789";
    char dst1[10]="1111111111";
    char src1[10]="";
    char dst2[10]="1111111111";
    char src3[10]="5\0";
    char dst4[10]="1";
    ck_assert_str_eq(s21_strncpy(dst1, src, 4), strncpy(dst1, src, 4));
    ck_assert_str_eq(s21_strncpy(dst2, src1, 4), strncpy(dst2, src1, 4));
    ck_assert_str_eq(s21_strncpy(dst4, src3, 4), strncpy(dst4, src3, 4));
}
END_TEST
START_TEST(s21_strcspn_test) {
#line 150
    char str[10]="0123456789";
    char sym[10]="9876";
    char str45[10] = "abcdefg";
    char sym45[10] = "abc";
    char str34[10] = "ABCD";
    char sym34[10] = "AB";
    ck_assert_uint_eq(s21_strcspn(str, sym), strcspn(str, sym));
    ck_assert_uint_eq(s21_strcspn(str45, sym45), strcspn(str45, sym45));
    ck_assert_uint_eq(s21_strcspn(str34, sym34), strcspn(str34, sym34));
}
END_TEST
START_TEST(s21_strerror_test) {
#line 162
    ck_assert_str_eq(s21_strerror(3), strerror(3));
    ck_assert_str_eq(s21_strerror(56), strerror(56));
    ck_assert_str_eq(s21_strerror(230), strerror(230));
}
END_TEST
START_TEST(s21_strlen_test) {
#line 167
    char strNEW[11] = "0123456789";
    char strR[11] = "abcdef";
    char strC[11] = "GGGG";
    ck_assert_int_eq(s21_strlen(strNEW), strlen(strNEW));
    ck_assert_int_eq(s21_strlen(strR), strlen(strR));
    ck_assert_int_eq(s21_strlen(strC), strlen(strC));
}
END_TEST
START_TEST(s21_strpbrk_test) {
#line 175
    char strNEW1[11] = "0123456789";
    char sym1[10] = "369";
    char frw[16] = "ABCSFER";
    char sym2[10] = "S";
    char frw1[16] = "abcderfgh";
    char sym3[10] = "f";
    ck_assert_str_eq(s21_strpbrk(strNEW1, sym1), strpbrk(strNEW1, sym1));
    ck_assert_str_eq(s21_strpbrk(frw, sym2), strpbrk(frw, sym2));
    ck_assert_str_eq(s21_strpbrk(frw1, sym3), strpbrk(frw1, sym3));
}
END_TEST
START_TEST(s21_strrchr_test) {
#line 186
    char strr[11]="0163456769";
    int chr = '6';
    char rand[11]="abcdehc";
    char chd = 'c';
    char opr[12]="ABNVDF";
    char xch = 'V';
    ck_assert_str_eq(s21_strrchr(strr, chr), strrchr(strr, chr));
    ck_assert_str_eq(s21_strrchr(rand, chd), strrchr(rand, chd));
    ck_assert_str_eq(s21_strrchr(opr, xch), strrchr(opr, xch));
}
END_TEST
START_TEST(s21_strspn_test) {
#line 197
    char str555[10]="0123456789";
    char sym555[10]="9876";
    char str[11]="0123456789";
    char sym[10]="210";
    char str1[11]="abcgdefggg";
    char sym1[10]="g";
    ck_assert_uint_eq(s21_strspn(str555, sym555), strspn(str555, sym555));
    ck_assert_int_eq(s21_strspn(str, sym), strspn(str, sym));
    ck_assert_int_eq(s21_strspn(str1, sym1), strspn(str1, sym1));
}
END_TEST
START_TEST(s21_strstr_test) {
#line 208
    char str144[11]="0123456789";
    char str244[10]="345";
    char str344[20] = "ABCDEFGF";
    char str444[20] = "ABCD";
    char str222[20] = "abcsdr";
    char str122[20] = "abc";
    ck_assert_str_eq(s21_strstr(str144, str244), strstr(str144, str244));
    ck_assert_str_eq(s21_strstr(str344, str444), strstr(str344, str444));
    ck_assert_str_eq(s21_strstr(str222, str122), strstr(str222, str122));
}
END_TEST
START_TEST(s21_strtok_test) {
#line 219
    char str[124]="test1/test2/test3/test4";
    char sep[10]="/";
    char str65[100] = "abcdAefghAjurjA";
    char sep65[10] = "A";
    char str165[100] = "ABCDaaaABCDaABCDaaa";
    char sep66[10] = "a";
    char str32[22] = "frfe";
    char sep67[34] =" ";
    char str31[22] = "frfe";
    char sep62[34] ="";
    ck_assert_str_eq(s21_strtok(str, sep), strtok(str, sep));
    ck_assert_str_eq(s21_strtok(str65, sep65), strtok(str65, sep65));
    ck_assert_str_eq(s21_strtok(str165, sep66), strtok(str165, sep66));
    ck_assert_str_eq(s21_strtok(str32, sep67), strtok(str32, sep67));
    ck_assert_str_eq(s21_strtok(str31, sep62), strtok(str31, sep62));
}
END_TEST
START_TEST(s21_sprintf_test) {
#line 236
    char str1[100]={0};
    char str2[100]={0};
    char str3[100]={0};
    char str4[100]={0};
    char str5[100]={0};
    char str6[100]={0};
    char str7[100]={0};
    char str8[100]={0};
    char str9[100]={0};
    char str10[100]={0};
    char str11[100]={0};
    char str12[100]={0};
    char str13[100]={0};
    char str14[100]={0};
    char str15[100]={0};
    char str16[100]={0};
    char p = '$';
    int n = 0;
    s21_sprintf(str1, "%c%s%5.2d%e%d", '$', "SASHA", -123, 0.000000000000000000044213166, 0);
    sprintf(str2, "%c%s%5.2d%e%d", '$', "SASHA", -123, 0.000000000000000000044213166, 0);
    s21_sprintf(str3, "%-15c%5s%+*.3d%.d", '$', "SASHA", 5, -123, 0);
    sprintf(str4, "%-15c%5s%+*.3d%.d", '$', "SASHA", 5, -123, 0);
    s21_sprintf(str5, "%7.2x%-#+3.f%1.1o", 123456, 15.0075, -765);
    sprintf(str6, "%7.2x%-#+3.f%1.1o", 123456, 15.0075, -765);
    s21_sprintf(str7, "%-7.35u%%%0+35.*ld%+ld", (unsigned int)-14234, 7, -1234563332314, 23568251976105);
    sprintf(str8, "%-7.35u%%%0+35.*ld%+ld", (unsigned int)-14234, 7, -1234563332314, 23568251976105);
    s21_sprintf(str9, "%p%#3.0E%#-7.4g%+f", &p, 0.038, 49.09900, 1.2);
    sprintf(str10, "%p%#3.0E%#-7.4g%+f", &p, 0.038, 49.09900, 1.2);
    s21_sprintf(str11, "%#+01.1f%3.0E%-13.5G", 12346326432.0, 0.038, 1.099);
    sprintf(str12, "%#+01.1f%3.0E%-13.5G", 12346326432.0, 0.038, 1.099);
    s21_sprintf(str13, "HELLO%s%f%+0g", " SEREGA", -12.13, -123e+12);
    sprintf(str14, "HELLO%s%f%+0g", " SEREGA", -12.13, -123e+12);
    s21_sprintf(str15, "%%ZzzZZz%-3.0s%+d%n%#-+f%#e", "", 35, &n, 0.0123, 1.0099);
    sprintf(str16, "%%ZzzZZz%-3.0s%+d%n%#-+f%#e", "", 35, &n, 0.0123, 1.0099);
    ck_assert_str_eq(str1, str2);
    ck_assert_str_eq(str3, str4);
    ck_assert_str_eq(str5, str6);
    ck_assert_str_eq(str7, str8);
    ck_assert_str_eq(str9, str10);
    ck_assert_str_eq(str11, str12);
    ck_assert_str_eq(str13, str14);
    ck_assert_str_eq(str15, str16);
}
END_TEST
START_TEST(s21_sscanf_test) {
#line 280
    int a, a1;
    double b, b1, b2, b3, b4, b5;
    int b6, b7;
    char str[100], str1[100], str2[100], str3[100];
    char c, c1;
    int n, n1;
    int *z, *z1;
    unsigned int v, v1, v2, v3, b11, b10, b9, b8;
    s21_sscanf("hello 123 5.49 TEST 0x143bbf 1.099e+3 $",
     "%5s %d%lf%4s%lE%lf%c%%", str, &a, &b, str2, &b2, &b4, &c);
    sscanf("hello 123 5.49 TEST 0x143bbf 1.099e+3 $",
     "%5s %d%lf%4s%lE%lf%c%%", str1, &a1, &b1, str3, &b3, &b5, &c1);
    s21_sscanf("0x0345bbf 001 012355", "%i%x%o%n", &b6, &b8, &b10, &n);
    sscanf("0x0345bbf 001 012355", "%i%x%o%n", &b7, &b9, &b11, &n1);
    s21_sscanf("0x01f", "%p", &z);
    sscanf("0x01f", "%p", &z1);
    s21_sscanf("00005 -012", "%o%o", &v, &v2);
    sscanf("00005 -012", "%o%o", &v1, &v3);
    ck_assert_str_eq(str, str1);
    ck_assert_int_eq(a, a1);
    ck_assert_int_eq(b, b1);
    ck_assert_str_eq(str2, str3);
    ck_assert_int_eq(b2, b3);
    ck_assert_int_eq(b4, b5);
    ck_assert_int_eq(c, c1);
    ck_assert_int_eq(b6, b7);
    ck_assert_int_eq(b8, b9);
    ck_assert_int_eq(b10, b11);
    ck_assert_int_eq(n, n1);
    ck_assert_int_eq(v, v1);
    ck_assert_int_eq(v2, v3);
}
END_TEST
START_TEST(test_upper) {
#line 311
    char string1[244] = "hvweertyyy";
    char *a = s21_to_upper(string1);
    char string3[244]="HVWEERTYYY";
    ck_assert_str_eq(a, string3);
    free(a);
    char string2[244] = "hello";
    char *b = s21_to_upper(string2);
    char string4[244]="HELLO";
    ck_assert_str_eq(b, string4);
    free(b);
    char string33[244] = " ";
    char *c = s21_to_upper(string33);
    char string6[244]=" ";
    ck_assert_str_eq(c, string6);
    free(c);
    char string34[244] = "DOYOUWANNASLEEP";
    char *d = s21_to_upper(string34);
    char string7[244]="DOYOUWANNASLEEP";
    ck_assert_str_eq(c, string7);
    free(d);
}
END_TEST
START_TEST(test_lower) {
#line 338
    char string01[244] = "SCHOOL";
    char *a1 = s21_to_lower(string01);
    char string03[244]="school";
    ck_assert_str_eq(a1, string03);
    free(a1);
    char string02[244] = "HELLO";
    char *b1 = s21_to_lower(string02);
    char string04[244]="hello";
    ck_assert_str_eq(b1, string04);
    free(b1);
    char string05[244] = "WORLD";
    char *c1 = s21_to_lower(string05);
    char string06[244]="world";
    ck_assert_str_eq(c1, string06);
    free(c1);
    char string07[244] = " ";
    char *d1 = s21_to_lower(string07);
    char string08[244]=" ";
    ck_assert_str_eq(d1, string08);
    free(d1);
}
END_TEST
START_TEST(test_insert) {
#line 363
    char mas[999];
    char *sourse1 = mas;
    sourse1 = s21_insert(sourse1, "hlo", 3);
    sourse1 = s21_insert(sourse1, "el", 1);
    free(sourse1);
    char B[1024] = "hello";
    ck_assert_str_eq("hello", B);
    char mas123[999];
    char *sourse2 = mas123;
    sourse2 = s21_insert(sourse2, "sc21", 6);
    sourse2 = s21_insert(sourse2, "hool", 2);
    free(sourse2);
    char C[1024] = "school21";
    ck_assert_str_eq("school21", C);
    char mas124[999];
    char *sourse3 = mas124;
    sourse3 = s21_insert(sourse3, "  ", 1);
    sourse3 = s21_insert(sourse3, " ", 0);
    free(sourse3);
    char D[1024] = " ";
    ck_assert_str_eq(" ", D);
}
END_TEST
START_TEST(test_trim) {
#line 395
    char string01[1024]="hello*****";
    char *string1;
    string1 = s21_trim(string01, "*");
    char str01[1024] = "hello";
    ck_assert_str_eq(str01, string1);
    free(string1);
    char string02[1024]="****hello*****";
    char *string12;
    string12 = s21_trim(string02, "*");
    char str012[1024] = "hello";
    ck_assert_str_eq(str012, string12);
    free(string12);
    char string03[1024]="hello";
    char *string123;
    string123 = s21_trim(string03, "*");
    char str0123[1024] = "hello";
    ck_assert_str_eq(str0123, string123);
    free(string123);
    char string04[1024]="*hey are you sick?*";
    char *string1234;
    string1234 = s21_trim(string04, "*");
    char str01234[1024] = "hey are you sick?";
    ck_assert_str_eq(str01234, string1234);
    free(string1234);
}
END_TEST
int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;
    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_memchr_test);
    tcase_add_test(tc1_1, s21_memcmp_test);
    tcase_add_test(tc1_1, s21_memcpy_test);
    tcase_add_test(tc1_1, s21_memmove_test);
    tcase_add_test(tc1_1, s21_memset_test);
    tcase_add_test(tc1_1, s21_strcat_test);
    tcase_add_test(tc1_1, s21_strncat_test);
    tcase_add_test(tc1_1, s21_strncmp_test);
    tcase_add_test(tc1_1, s21_strchr_test);
    tcase_add_test(tc1_1, s21_strcmp_test);
    tcase_add_test(tc1_1, s21_strcpy_test);
    tcase_add_test(tc1_1, s21_strncpy_test);
    tcase_add_test(tc1_1, s21_strcspn_test);
    tcase_add_test(tc1_1, s21_strerror_test);
    tcase_add_test(tc1_1, s21_strlen_test);
    tcase_add_test(tc1_1, s21_strpbrk_test);
    tcase_add_test(tc1_1, s21_strrchr_test);
    tcase_add_test(tc1_1, s21_strspn_test);
    tcase_add_test(tc1_1, s21_strstr_test);
    tcase_add_test(tc1_1, s21_strtok_test);
    tcase_add_test(tc1_1, s21_sprintf_test);
    tcase_add_test(tc1_1, s21_sscanf_test);
    tcase_add_test(tc1_1, test_upper);
    tcase_add_test(tc1_1, test_lower);
    tcase_add_test(tc1_1, test_insert);
    tcase_add_test(tc1_1, test_trim);
    srunner_run_all(sr, CK_VERBOSE);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);
    return nf == 0 ? 0 : 1;
}
